version: '3.9'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "8000:5000"  # Le conteneur reste en 5000, mais ton host utilisera 8000
    environment:
      - FLASK_ENV=development
